### ISSUE TITLE
Solve build fail problems and coverage issue

### ISSUE THREAD

**Issue by AidanRocke** [openworm/behavioral_syntax#18]
1) Build must pass
2) 100% coverage required.

**Comment by MichaelCurrie** [comment]
I believe https://github.com/AidanRocke/behavioral_syntax/pull/29 fixes your step number 1.

**Comment by AidanRocke** [comment]
Just had it merged. I'm not yet sure how to do 100% test coverage or whether that's even necessary. But, I think it might be a good idea to have some measure of what percentage of the codebase has been tested.

It's definitely not high priority but here's more info: http://blog.jbrains.ca/permalink/on-100-unit-test-coverage-and-other-nonsensical-ideas

**Comment by ghost** [comment]
In retrospect this is a regular issue. Will close in order to avoid creating 'issue noise'.
