### ISSUE TITLE
does C. Elegans locomotion stabilize after a certain point?

### ISSUE THREAD

**Issue by AidanRocke** [openworm/behavioral_syntax#27]
If it did then similar start and end times would be an unnecessary requirement for sequences of frames used as input. If it did, we would only require that sequences of frames either be of a certain minimal length. Given that the n-gram discovery rate plateaus I have reason to believe that patterns of locomotion might stabilize after some point.

**Comment by AidanRocke** [comment]
In any case, I expect that the discovery rate for data-rich environments should be greater for a greater period of time compared to data-poor environments. This prediction can be tested for off-food vs on-food environments.

**Comment by ghost** [comment]
This is related to the minimum description length principle which is difficult to evaluate at present due to the lack of ecologically-realistic C. Elegans locomotion lab data.
