### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by AidanRocke** [openworm/behavioral_syntax#30]
1. cythonize what can be cythonized. start here: http://docs.cython.org/src/userguide/numpy_tutorial.html#numpy-tutorial
2. use itertools or some better alternative to loops in Python
3. consider using PyParallel: http://www.infoq.com/articles/PyParallel

The following program for example: https://github.com/AidanRocke/behavioral_syntax/blob/master/models/discrete_models/discretization/posture_probabilities.py

takes about 2 mins to run for just one video with about 20000 frames. A heatmap of temporal posture distribution represents only a fraction of the analysis that will be done. Not even 5%. 

Now, if we're considering a sample size of at least 30 different worms this would mean that the time taken to produce a lab report would be greater than 2 hours. And that's really the lower bound.

**Comment by MichaelCurrie** [comment]
In my opinion I think 2 hours is okay if we are comparing 30 different worms.  Before worrying about optimizing I would want to know:

1) How long did André's Matlab code take to do the same analysis?
2) How long would the full analysis of all worm videos (i.e. 10 TB of videos) we are interested in take on a normal computer?

If the answer to 1 is "a similar amount of time" and 2 is "less than a week", I think we can deploy the virtual resources it would take to perform the analysis in a reasonable amount of time.  AWS has very large instances we could use to bring the time down.

All I'm saying is, getting the thing done and integrated with [OWAT](https://github.com/openworm/open-worm-analysis-toolbox) to me is much more important than optimization.
