### ISSUE TITLE
Turing Test assumptions??

### ISSUE THREAD

**Issue by AidanRocke** [openworm/behavioral_syntax#40]
The Turing Test assumes that it's sufficient to test for some terminal state(human intelligence) in terms of ability and assume that the machine is intelligent. But, if intelligence is the ability to adapt rather than a certain level of intelligence then we should be testing for the ability to evolve rather than obsessing over some measure of similarity.

**Comment by MichaelCurrie** [comment]
Possibly relevant: here is a paper discussing the Turing test as it relates to worms:  https://github.com/openworm/open-worm-analysis-toolbox/blob/master/documentation/Movement%20Validation%20White%20Paper.md

**Comment by AidanRocke** [comment]
That paper addresses exactly Turing Tests, which I have doubts on. A strong Turing Test wouldn't simply be binary...it would serve as a [metric](https://en.wikipedia.org/wiki/Metric_(mathematics)) so that we can get an idea of how close the OpenWorm project is getting to its final destination. 

But, a complementary measure which might be useful is some general measure of adaptability or 'intelligence'. I think that Shane Legg of DeepMind has some interesting ideas on how we might do this: http://www.vetta.org/documents/Benelearn-UniversalIntelligence-Talk.pdf

**Comment by ghost** [comment]
Probably my final comment: there is no such thing as a perfect Turing Test. If we think of it as a distance function that maps agents to values in (0,1) in theory you can come up with an infinite number of fake worms that game the test. In theory there's nothing that would prevent the test from being almost always wrong unless we have reliable prior information about the set of possible digital worms.
