### ISSUE TITLE
Organize repository around tests for global and local behavioral patterns

### ISSUE THREAD

**Issue by ghost** [openworm/behavioral_syntax#41]
Examples of local behavioral patterns would include:
1) a deterministic response to a stimulus: tests/local/deterministic_response.py
2) How the worm might perform particular movements(i.e. muscle control): omega_pirouette_reversal.py

Examples of global behavioral patterns would include:
1) slower average speed in the second half of a 15 minute video. This has been consistently observed. 
2) Lévy flight foraging behavior when searching through an environment that doesn't contain any food. 
3) Following chemical gradients when placed in a petri-dish with a chemical mixture.
4) Decreasing discovery rate of new patterns: discovery_rate.py

**Comment by AidanRocke** [comment]
Ongoing.
